version: '3.8'

services:
  field_report:
    build:
      context: ../field_report
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rapport
      DB_USER: field
      DB_PASSWORD: rootpass
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - ../field_report:/var/www/html

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: rapport
      POSTGRES_USER: field
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres

volumes:
  pg-data:
