version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rapport
      DB_USER: field
      DB_PASSWORD: rootpass
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - "3000:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: rapport
      POSTGRES_USER: field
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres

volumes:
  pg-data:
